package cn.dancingsnow.neoecoae.gui.ldlib.state;

import java.util.List;
import net.minecraft.core.BlockPos;
import net.minecraft.world.item.ItemStack;

public record NECraftingUiState(
        BlockPos pos,
        boolean formed,
        boolean active,
        int workerCount,
        int parallelCount,
        int patternBusCount,
        int threadCount,
        int runningThreadCount,
        boolean overclocked,
        boolean activeCooling,
        boolean autoClearCoolingWaste,
        int selectedBuildLength,
        boolean buildInProgress,
        int previewMissingBlocks,
        int previewConflictBlocks,
        int previewReusedBlocks,
        int previewRequiredItems,
        String previewStatusKey,
        int previewStatusArg1,
        int previewStatusArg2,
        long energyUsage,
        long coolantAmount,
        long coolantCapacity,
        int availableThreads,
        int effectiveParallel,
        int maxRecipeSlots,
        int occupiedRecipeSlots,
        int batchParallel,
        long performanceAverageNanos,
        List<NECraftingRecipeUiEntry> recipeEntries,
        List<NECraftingBatchUiState> batchStates,
        List<ItemStack> workerCraftOutputs,
        List<Integer> parallelCoreTiers,
        List<NECraftingModuleCell> moduleCells) {
    public static NECraftingUiState empty(BlockPos pos) {
        return new NECraftingUiState(
                pos,
                false,
                false,
                0,
                0,
                0,
                0,
                0,
                false,
                false,
                false,
                1,
                false,
                0,
                0,
                0,
                0,
                "gui.neoecoae.multiblock.status.idle",
                0,
                0,
                0L,
                0L,
                0L,
                0,
                0,
                0,
                0,
                0,
                0L,
                List.of(),
                List.of(),
                List.of(),
                List.of(),
                List.of());
    }
}
