modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/DancingSnow0517/NeoECOAEExtension/issues"
accessTransformers=[]

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://api.modrinth.com/updates/neoecoae/forge_updates.json"
displayURL="https://github.com/DancingSnow0517/NeoECOAEExtension"
logoFile="icon.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ae2"
    mandatory=true
    versionRange="[15.4.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ldlib"
    mandatory=true
    versionRange="[1.0.33,1.0.34)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jade"
    mandatory=false
    versionRange="[11.13.0,)"
    ordering="AFTER"
    side="BOTH"

[mc-publish]
    modrinth="udZtKfzP"
    curseforge=1460639
    loaders=["forge"]
    game-versions=["1.20.1"]
